name: key_overlays
description: "An extraordinary Package to handle overlays in flutter"
version: 0.0.2
repository: https://github.com/boginni/boginni_utils

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  boginni_utils: ^0.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2